name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          sudo apt-get install libpcap-dev
          cargo build --release --target-dir ./target
          ls -al target/release/
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mentorust
        path: ./target/release  # 请根据你实际编译后文件的路径进行修改
